sonar.organization=nazia-karim-khan-oishee
sonar.projectKey=Nazia-Karim-Khan-Oishee_angular-web
sonar.projectName=angular-web

sonar.sources=src
sonar.exclusions=**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/webapp/lcov.info

sonar.qualitygate.wait=true
